"""add_practice_words_table_for_real_time_practice

Revision ID: 166bf4cf086e
Revises: 4028cf04bbe8
Create Date: 2025-11-03 18:16:16.633368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '166bf4cf086e'
down_revision = '4028cf04bbe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('phonetics', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_path', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_words_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_words_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_words_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_practice_words_status'), ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_words_status'))
        batch_op.drop_index(batch_op.f('ix_practice_words_public_id'))
        batch_op.drop_index(batch_op.f('ix_practice_words_difficulty'))
        batch_op.drop_index(batch_op.f('ix_practice_words_category_id'))

    op.drop_table('practice_words')
    # ### end Alembic commands ###
