"""Drop rating/views columns from tutorials and quizzes

Revision ID: 35700fbecd71
Revises: e3a1b6eccc36
Create Date: 2025-10-31 02:00:52.209800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35700fbecd71'
down_revision = 'e3a1b6eccc36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('rating')
        batch_op.drop_column('views')

    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.drop_column('rating')
        batch_op.drop_column('views')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rating', mysql.DECIMAL(precision=3, scale=2), nullable=True))

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rating', mysql.DECIMAL(precision=3, scale=2), nullable=True))

    # ### end Alembic commands ###
