"""fix tutorial model - remove duplicate video columns and add subtitle support

Revision ID: 3f517bdfa406
Revises: 9c60ac96fde6
Create Date: 2025-10-27 00:27:58.100014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f517bdfa406'
down_revision = '9c60ac96fde6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.drop_column('video_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_data', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))

    # ### end Alembic commands ###
