"""Add user_progress table for tracking individual video completions

Revision ID: 4028cf04bbe8
Revises: 61d6a0444828
Create Date: 2025-11-02 15:28:17.221655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4028cf04bbe8'
down_revision = '61d6a0444828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=25), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tutorial_id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['tutorials.id'], ),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_progress_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_progress_series_id'), ['series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_progress_tutorial_id'), ['tutorial_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_progress_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_progress_tutorial_id'))
        batch_op.drop_index(batch_op.f('ix_user_progress_series_id'))
        batch_op.drop_index(batch_op.f('ix_user_progress_public_id'))

    op.drop_table('user_progress')
    # ### end Alembic commands ###
