"""Add tutorial series fields for Udemy-like functionality

Revision ID: 453c0fffb86b
Revises: 691e72ffda2e
Create Date: 2025-10-23 23:58:42.970895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453c0fffb86b'
down_revision = '691e72ffda2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bookmarks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tutorial_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tutorial_id')
    )
    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('parent_series_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('video_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('video_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('video_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('video_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('learning_objectives', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('prerequisites', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_preview', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('video_file_path', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_tutorials_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_tutorials_parent_series_id'), ['parent_series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tutorials_series_type'), ['series_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_tutorials_status'), ['status'], unique=False)
        batch_op.create_foreign_key(None, 'tutorials', ['parent_series_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tutorials_status'))
        batch_op.drop_index(batch_op.f('ix_tutorials_series_type'))
        batch_op.drop_index(batch_op.f('ix_tutorials_parent_series_id'))
        batch_op.drop_index(batch_op.f('ix_tutorials_difficulty'))
        batch_op.drop_column('video_file_path')
        batch_op.drop_column('is_preview')
        batch_op.drop_column('tags')
        batch_op.drop_column('prerequisites')
        batch_op.drop_column('learning_objectives')
        batch_op.drop_column('video_duration')
        batch_op.drop_column('video_description')
        batch_op.drop_column('video_title')
        batch_op.drop_column('video_order')
        batch_op.drop_column('parent_series_id')
        batch_op.drop_column('series_type')

    op.drop_table('user_bookmarks')
    # ### end Alembic commands ###
