"""add_google_id_to_accounts

Revision ID: 546562e90698
Revises: 2789d3fd847f
Create Date: 2025-11-06 01:05:30.545959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546562e90698'
down_revision = '2789d3fd847f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_accounts_google_id'), ['google_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_google_id'))
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
