"""add_2fa_secret_to_accounts

Revision ID: 55d92898d5d8
Revises: 546562e90698
Create Date: 2025-11-06 01:24:41.036281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d92898d5d8'
down_revision = '546562e90698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_2fa_secret', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('_2fa_secret')

    # ### end Alembic commands ###
