"""add quiz series functionality to quiz model

Revision ID: 5f30ffa0855f
Revises: fcd160e1f500
Create Date: 2025-10-27 02:07:47.049349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f30ffa0855f'
down_revision = 'fcd160e1f500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('parent_series_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quiz_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quiz_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('quiz_description', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_quizzes_parent_series_id'), ['parent_series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quizzes_series_type'), ['series_type'], unique=False)
        batch_op.create_foreign_key(None, 'quizzes', ['parent_series_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_quizzes_series_type'))
        batch_op.drop_index(batch_op.f('ix_quizzes_parent_series_id'))
        batch_op.drop_column('quiz_description')
        batch_op.drop_column('quiz_title')
        batch_op.drop_column('quiz_order')
        batch_op.drop_column('parent_series_id')
        batch_op.drop_column('series_type')

    # ### end Alembic commands ###
