"""Add transcription processing fields

Revision ID: 61d6a0444828
Revises: 77b34d0ec68a
Create Date: 2025-10-31 20:26:21.609576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d6a0444828'
down_revision = '77b34d0ec68a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('gdrive_file_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('colab_job_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('processed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('duration_seconds', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transcriptions_colab_job_id'), ['colab_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcriptions_gdrive_file_id'), ['gdrive_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcriptions_processing_status'), ['processing_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcriptions_processing_status'))
        batch_op.drop_index(batch_op.f('ix_transcriptions_gdrive_file_id'))
        batch_op.drop_index(batch_op.f('ix_transcriptions_colab_job_id'))
        batch_op.drop_column('duration_seconds')
        batch_op.drop_column('processed_at')
        batch_op.drop_column('colab_job_id')
        batch_op.drop_column('gdrive_file_id')
        batch_op.drop_column('processing_status')

    # ### end Alembic commands ###
