"""add login attempt tracking and password reset rate limiting

Revision ID: 62cace92ed4a
Revises: a1c819795bb6
Create Date: 2025-11-08 00:48:24.101355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62cace92ed4a'
down_revision = 'a1c819795bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('account_locked_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_password_reset_request', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_accounts_account_locked_until'), ['account_locked_until'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_account_locked_until'))
        batch_op.drop_column('last_password_reset_request')
        batch_op.drop_column('account_locked_until')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
