"""Add enhanced fields to tutorials table

Revision ID: 691e72ffda2e
Revises: e129e754f37e
Create Date: 2025-10-23 02:37:33.982410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691e72ffda2e'
down_revision = 'e129e754f37e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='draft'))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=20), nullable=False, server_default='beginner'))
        batch_op.add_column(sa.Column('author', sa.String(length=255), nullable=False, server_default='System'))
        batch_op.add_column(sa.Column('thumbnail_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('rating', sa.DECIMAL(precision=3, scale=2), nullable=True, server_default='0.0'))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
        batch_op.create_index(batch_op.f('ix_tutorials_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_tutorials_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tutorials_status'))
        batch_op.drop_index(batch_op.f('ix_tutorials_difficulty'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('rating')
        batch_op.drop_column('views')
        batch_op.drop_column('thumbnail_path')
        batch_op.drop_column('author')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
