"""Drop rating columns from tutorials and quizzes

Revision ID: 77b34d0ec68a
Revises: 35700fbecd71
Create Date: 2025-10-31 02:22:17.654920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b34d0ec68a'
down_revision = '35700fbecd71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=False))

    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.drop_column('views')

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('views')

    # ### end Alembic commands ###
