"""Add video_data field to tutorials table

Revision ID: 7a941e912377
Revises: 453c0fffb86b
Create Date: 2025-10-24 18:41:13.753751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a941e912377'
down_revision = '453c0fffb86b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.drop_column('video_data')

    # ### end Alembic commands ###
