"""phase 2: add missing fields to quiz model for education module

Revision ID: 8a9d11d7c25d
Revises: 2f62629ec896
Create Date: 2025-10-26 20:29:38.377256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9d11d7c25d'
down_revision = '2f62629ec896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=20), nullable=False, server_default='beginner'))
        batch_op.add_column(sa.Column('author', sa.String(length=255), nullable=False, server_default='System'))
        batch_op.add_column(sa.Column('thumbnail_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('rating', sa.DECIMAL(precision=3, scale=2), nullable=True, server_default='0.0'))
        batch_op.add_column(sa.Column('total_questions', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('estimated_duration', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.create_index(batch_op.f('ix_quizzes_difficulty'), ['difficulty'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quizzes_difficulty'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('tags')
        batch_op.drop_column('estimated_duration')
        batch_op.drop_column('total_questions')
        batch_op.drop_column('rating')
        batch_op.drop_column('views')
        batch_op.drop_column('thumbnail_path')
        batch_op.drop_column('author')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
