"""fix tutorial table - remove duplicate video_file_path and add subtitle_path

Revision ID: 9c60ac96fde6
Revises: d25e64fbcdef
Create Date: 2025-10-27 00:03:48.075794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c60ac96fde6'
down_revision = 'd25e64fbcdef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle_path', sa.String(length=255), nullable=True))
        batch_op.drop_column('video_file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_file_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.drop_column('subtitle_path')

    # ### end Alembic commands ###
