"""add review system fields to user_bookmarks table

Revision ID: d25e64fbcdef
Revises: 8a9d11d7c25d
Create Date: 2025-10-26 21:42:55.012412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25e64fbcdef'
down_revision = '8a9d11d7c25d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_bookmarks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_bookmarks', schema=None) as batch_op:
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('review_text')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
