"""initial schema

Revision ID: e129e754f37e
Revises: 
Create Date: 2025-10-20 17:22:27.518095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e129e754f37e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('profile_image_path', sa.String(length=255), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_account_type'), ['account_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_accounts_public_id'), ['public_id'], unique=True)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_public_id'), ['public_id'], unique=True)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=25), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('generated_date', sa.DateTime(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_public_id'), ['public_id'], unique=True)

    op.create_table('administrators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quizzes_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quizzes_public_id'), ['public_id'], unique=True)

    op.create_table('tutorials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_path', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tutorials_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tutorials_public_id'), ['public_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accessibility_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('font_size', sa.String(length=20), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=25), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attached_file_path', sa.String(length=255), nullable=True),
    sa.Column('submission_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_feedback_submitted_by_user_id'), ['submitted_by_user_id'], unique=False)

    op.create_table('login_activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_activity_user_id'), ['user_id'], unique=False)

    op.create_table('notification_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reminder_frequency', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('practice_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=25), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reference_video_path', sa.String(length=255), nullable=False),
    sa.Column('session_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_sessions_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_practice_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=25), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('answers_json', sa.Text(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_attempts_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_quiz_id'), ['quiz_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('video_clip_path', sa.String(length=255), nullable=False),
    sa.Column('correct_answer', sa.String(length=255), nullable=False),
    sa.Column('incorrect_options', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_questions_quiz_id'), ['quiz_id'], unique=False)

    op.create_table('third_party_apps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=False),
    sa.Column('date_granted', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('third_party_apps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_third_party_apps_user_id'), ['user_id'], unique=False)

    op.create_table('transcriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=25), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('timestamps_json', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('video_source_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcriptions_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_transcriptions_user_id'), ['user_id'], unique=False)

    op.create_table('user_bookmarks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tutorial_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tutorial_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_bookmarks')
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transcriptions_public_id'))

    op.drop_table('transcriptions')
    with op.batch_alter_table('third_party_apps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_third_party_apps_user_id'))

    op.drop_table('third_party_apps')
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_questions_quiz_id'))

    op.drop_table('quiz_questions')
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_quiz_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_public_id'))

    op.drop_table('quiz_attempts')
    with op.batch_alter_table('practice_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_practice_sessions_public_id'))

    op.drop_table('practice_sessions')
    op.drop_table('notification_settings')
    with op.batch_alter_table('login_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_activity_user_id'))

    op.drop_table('login_activity')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_submitted_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_public_id'))

    op.drop_table('feedback')
    op.drop_table('accessibility_settings')
    op.drop_table('users')
    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tutorials_public_id'))
        batch_op.drop_index(batch_op.f('ix_tutorials_category_id'))

    op.drop_table('tutorials')
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quizzes_public_id'))
        batch_op.drop_index(batch_op.f('ix_quizzes_category_id'))

    op.drop_table('quizzes')
    op.drop_table('administrators')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_public_id'))

    op.drop_table('reports')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_public_id'))

    op.drop_table('categories')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_public_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_email'))
        batch_op.drop_index(batch_op.f('ix_accounts_account_type'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
