"""Initial schema with reviews table

Revision ID: e3a1b6eccc36
Revises: 
Create Date: 2025-10-31 01:05:44.057451

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3a1b6eccc36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=25), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name='uq_review_user_target')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_reviews_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_target_type'), ['target_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.alter_column('attempt_number',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('passed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.alter_column('passed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('attempt_number',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_target_type'))
        batch_op.drop_index(batch_op.f('ix_reviews_target_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_public_id'))

    op.drop_table('reviews')
    # ### end Alembic commands ###
