"""add missing tutorial fields - video_file_path and video_data

Revision ID: e9f8e831ffdf
Revises: 3f517bdfa406
Create Date: 2025-10-27 01:17:29.900417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9f8e831ffdf'
down_revision = '3f517bdfa406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_file_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('video_data', sa.Text(), nullable=True))
        batch_op.drop_column('subtitle_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.drop_column('video_data')
        batch_op.drop_column('video_file_path')

    # ### end Alembic commands ###
