"""fix tutorial model - add subtitle support and remove duplicate columns

Revision ID: fcd160e1f500
Revises: e9f8e831ffdf
Create Date: 2025-10-27 01:28:13.012442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fcd160e1f500'
down_revision = 'e9f8e831ffdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle_path', sa.String(length=255), nullable=True))
        batch_op.drop_column('video_file_path')
        batch_op.drop_column('video_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_data', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.add_column(sa.Column('video_file_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.drop_column('subtitle_path')

    # ### end Alembic commands ###
